chat/urls.py
from django.urls import path
from .views import chat, room, send, getmessages

app_name = "chat"

urlpatterns = [
    path('', chat, name='chat'),
    path("room/<str:friend>",room,name='room'),
    path("send/",send,name='send'),
    path("getmessages/<str:friend>",getmessages,name='getmessages'),
]

favfreelance/urls.py
from django.urls import path
from . import views

app_name = "favfreelance"

urlpatterns = [
    path('favelist', views.favelist, name='favelist'),
]

freelanceAdPage/urls.py
from django.urls import path

from . import views

app_name = "freelanceAdPage"

urlpatterns = [
    path('browse_page', views.browse_page, name='browse_page'),
    path('freelance_ad_page/<str:pk>/', views.freelance_ad_page, name='freelance_ad_page'),
    path('create_ad_page', views.create_ad_page, name='create_ad_page'),
    path('created_freelance_ad_page_list', views.created_freelance_ad_page_list, name="created_freelance_ad_page_list"),
    path('update_ad_page/<str:pk>/', views.update_ad_page, name='update_ad_page'),
    path('delete_ad_page/<str:pk>/', views.delete_ad_page, name='delete_ad_page'),
    path('review/<str:ad>',views.review,name='review')
]

freelanceadvertisement/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('freelanceAdPage/', include('freelanceAdPage.urls')),
    path('', include('home.urls')),
    path('chat/', include('chat.urls')),
    path('favfreelance/', include('favfreelance.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Anggota(AbstractUser):
	username = models.CharField(max_length=50, unique=True)
	email = models.EmailField()
	password1 = models.CharField(max_length=50)
	password2 = models.CharField(max_length=50)
	ROLES = (
		(1,'Freelancer'),
		(2,'Employer'),
	)
	role = models.IntegerField(choices=ROLES, default=1)

home/forms.py
from django import forms
from .models import Anggota
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
	class Meta:
		model = Anggota
		fields = ['username','email','password1','password2','role']
		widgets = {
		'username': forms.TextInput(attrs={'class':'input','placeholder':'Username...'}),
		'email': forms.TextInput(attrs={'class':'input','placeholder':'Email...'}),
		'role': forms.Select(choices=((1,'Freelancer'),(2,'Employer')))
		}

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)
		self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Password...'})
		self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Retype password...'})

home/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory
from .forms import *
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def home(request):
    print(request.user)
    return render(request, 'home.html')

def signup(request):
    if request.user.is_authenticated:
            return redirect('/')
    else:
        form = SignUpForm()
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid() :
                username = form.cleaned_data.get('username')
                user = form.save()
                print(user)
                messages.success(request, username)
                return render(request, 'home.html')
            else:
                print(form.errors)
    context = {'form':form}
    return render(request, 'signup.html', context)


def login_view(request):
    if request.user.is_authenticated:
            return redirect('/')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            print(username)
            password = request.POST.get('password')
            print(password)
            user = authenticate(request, username=username, password=password)
            print(user)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.info(request, 'Username OR password is incorrect')
    context = {}
    return render(request, 'login.html', context)

def logout_view(request):
    logout(request)
    return redirect('login/')

home/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Home</title>
  </head>
  {% extends 'navbar.html' %} {% load static %} {% block content %}

  <body>
    <div class="container">
        <h1>Home</h1>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
  {% endblock %}
</html>

home/templates/login.html
{% load static %} 
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'login/styles.css' %}">
    <title>Login</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Home</title>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freelanceAdPage:browse_page' %}">Browse Freelance</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              User Portal
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% if request.user.is_anonymous %}
              <li><a class="dropdown-item" href="#">About</a></li>
              <li><a class="dropdown-item" href="{% url 'home:signup' %}">Register</a></li>
              <li><a class="dropdown-item" href="{% url 'home:login' %}">Login</a></li>
              {% else %}
              <li><a class="dropdown-item" href="#">About</a></li>
              <li><a class="dropdown-item" href="#">Dashboard</a></li>
              <li><a class="dropdown-item" href="{% url 'chat:chat' %}">Chat</a></li>
              <li><a class="dropdown-item" href="{% url 'home:logout' %}">Logout</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  <body class="gradient-custom" style="height: calc(100vh - 56px);">
    <section>
      <div class="container">
        <div class="row d-flex justify-content-center align-items-center">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white mt-4" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4 pb-5">

                  <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                  <p class="text-white-50 mb-5">Please enter your username and password!</p>

                  <form method="POST"> 
                    {% csrf_token %}
                    <div class="form-outline form-white mb-4">
                    <input type="text" id="typeUsernameX" class="form-control form-control-lg" name="username" />
                    <label class="form-label" for="typeUsernameX">Username</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="password" id="typePasswordX" class="form-control form-control-lg" name="password" />
                    <label class="form-label" for="typePasswordX">Password</label>
                  </div>
                  <input class="btn btn-outline-light btn-lg px-5" type="submit" value="Login">
                </div>
                  </form>
                <div>
                  <p class="mb-0">Don't have an account? <a href="{% url 'home:signup' %}" class="text-white-50 fw-bold">Sign Up</a></p>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
  {% endblock %}
</html>

home/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'freelanceAdPage:browse_page' %}">Browse Freelance</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'favfreelance:favelist' %}">Favorite Freelance</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User Portal
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% if request.user.is_anonymous %}
            <li><a class="dropdown-item" href="#">About</a></li>
            <li><a class="dropdown-item" href="{% url 'home:signup' %}">Register</a></li>
            <li><a class="dropdown-item" href="{% url 'home:login' %}">Login</a></li>
            {% else %}
            <li><a class="dropdown-item" href="#">About</a></li>
            <li><a class="dropdown-item" href="#">Dashboard</a></li>
            <li><a class="dropdown-item" href="{% url 'chat:chat' %}">Chat</a></li>
            <li><a class="dropdown-item" href="{% url 'home:logout' %}">Logout</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}

home/templates/signup.html
{% load static %}
<!doctype html>
  <html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'login/styles.css' %}">
    <title>Sign Up</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Home</title>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'freelanceAdPage:browse_page' %}">Browse Freelance</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              User Portal
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% if request.user.is_anonymous %}
              <li><a class="dropdown-item" href="#">About</a></li>
              <li><a class="dropdown-item" href="{% url 'home:signup' %}">Register</a></li>
              <li><a class="dropdown-item" href="{% url 'home:login' %}">Login</a></li>
              {% else %}
              <li><a class="dropdown-item" href="#">About</a></li>
              <li><a class="dropdown-item" href="#">Dashboard</a></li>
              <li><a class="dropdown-item" href="{% url 'chat:chat' %}">Chat</a></li>
              <li><a class="dropdown-item" href="{% url 'home:logout' %}">Logout</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}

  <body class="gradient-custom">
    <section style="height: calc(100vh - 56px);">
  <div class="mask d-flex align-items-center gradient-custom-3">
    <div class="container">
      <div class="row d-flex justify-content-center align-items-center">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card bg-dark text-white mt-5" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

              <form method="POST"> 
                {% csrf_token %}

                <div class="d-flex justify-content-center form-outline mb-4">
                  {{ form.username }}
                </div>

                <div class="d-flex justify-content-center form-outline mb-4">
                  {{ form.email }}
                </div>

                <div class="d-flex justify-content-center form-outline mb-4">
                  {{ form.password1 }}
                </div>

                <div class="d-flex justify-content-center form-outline mb-4">
                  {{ form.password2 }}
                </div>

                <div class="d-flex justify-content-center form-outline mb-4">
                  {{ form.role }}
                </div>

                <div class="d-flex justify-content-center">
                  <input type="submit" value="Register" class="btn btn-outline-light btn-lg px-5">
                </div>

                <p class="text-center text-muted mt-3 mb-0">Have already an account? <a href="{% url 'home:login' %}" class="text-white-50 fw-bold text-body"><u>Login here</u></a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
  {% endblock %}
  </html>