chat/urls.py
from django.urls import path
from .views import chat, room, send, getmessages

app_name = "chat"

urlpatterns = [
    path('', chat, name='chat'),
    path("room/<str:friend>",room,name='room'),
    path("send/",send,name='send'),
    path("getmessages/<str:friend>",getmessages,name='getmessages'),
]

freelanceAdPage/urls.py
from django.urls import path

from . import views

app_name = "freelanceAdPage"

urlpatterns = [
    path('browse_page', views.browse_page, name='browse_page'),
    path('freelance_ad_page/<str:pk>/', views.freelance_ad_page, name='freelance_ad_page'),
    path('create_ad_page', views.create_ad_page, name='create_ad_page'),
    path('created_freelance_ad_page_list', views.created_freelance_ad_page_list, name="created_freelance_ad_page_list"),
    path('update_ad_page/<str:pk>/', views.update_ad_page, name='update_ad_page'),
    path('delete_ad_page/<str:pk>/', views.delete_ad_page, name='delete_ad_page'),
    path('review/<str:ad>',views.review,name='review')
]

freelanceadvertisement/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('freelanceAdPage/', include('freelanceAdPage.urls')),
    path('', include('home.urls')),
    path('chat/', include('chat.urls')),
    path('favfreelance/', include('favfreelance.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),
]

freelanceAdPage/models.py
from django.db import models
from django.core.validators import *
from datetime import datetime

# Create your models here.

class AdPage(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    additional_info = models.TextField(max_length=200)
    price = models.IntegerField()
    creator = models.CharField(max_length=1000)

    def __str__(self):
        return self.title

class rateAndComment(models.Model):
    user=models.CharField(max_length=120)
    ad = models.CharField(max_length=1000000)
    review=models.CharField(max_length=1000000)
    score=(
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5),
    )
    rating=models.IntegerField(choices=score,default=3)
    date=models.DateTimeField(default=datetime.now,blank=True)

freelanceAdPage/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AdPageForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Your Freelance name", "class": "form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Your Freelance name", "class": "form-control"}))
    additional_info = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Additional Information", "class": "form-control"}))
    price = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={"placeholder": "Minimum price is 1", "class": "form-control"}))
    creator = forms.CharField(widget=forms.TextInput(attrs={"type": "hidden"}))

freelanceAdPage/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory
from .forms import *
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def browse_page(request):
    freelances = AdPage.objects.all()
    count = len(freelances)
    if request.method == "POST":
        search_freelance = request.POST.get("search_freelance")
        freelances = AdPage.objects.filter(title__contains=search_freelance)
        count = len(freelances)
    context = {
        "freelances": freelances,
        "count": count
    }
    return render(request, 'browse_page.html', context)

def freelance_ad_page(request, pk):
    ad = AdPage.objects.get(id=pk)
    unsorted_reviews = rateAndComment.objects.all().filter(ad=pk)
    if request.user.is_anonymous:
        role = 3
    else:
        role = request.user.role
    if len(unsorted_reviews) < 1:
        context = {
        "ad": ad,
        "role": role,
        "count": len(unsorted_reviews)
    }
    else:
        review=sorted(list(unsorted_reviews.values()),key=lambda k:k['date'])[::-1][0]
        context = {
            "ad": ad,
            "role": role,
            "review": review,
            "count": len(unsorted_reviews)
        }
    return render(request, 'freelance_ad_page.html', context)

@login_required
def create_ad_page(request):
    if request.user.role == 1:
        form = AdPageForm(initial={'creator': request.user})
        if request.method == "POST":
            form = AdPageForm(request.POST)
            if form.is_valid():
                AdPage.objects.create(**form.cleaned_data)
                form = AdPageForm()
                return redirect("/freelanceAdPage/created_freelance_ad_page_list")
        context = {
            'form' : form
        }
        return render(request, 'create_ad_page.html', context)
    else:
        return redirect('/')

@login_required
def created_freelance_ad_page_list(request):
    if request.user.role == 1:
        querySet = AdPage.objects.filter(creator=request.user)
        context = {
            "AdPage": querySet
        }
        return render(request, 'freelance_ad_created_list.html', context)
    else:
        return redirect('/')

@login_required
def update_ad_page(request, pk):
    if request.user.role == 1:
        freelance = AdPage.objects.filter(id=pk).values()[0]
        title = freelance['title']
        form = AdPageForm(initial={'title': freelance['title'], 'description': freelance['description'], 'additional_info': freelance['additional_info'], "price": freelance["price"], "creator": freelance["creator"]})
        if request.method == "POST":
            form = AdPageForm(request.POST)
            if form.is_valid():
                AdPage.objects.filter(id=pk).update(**form.cleaned_data)
                return redirect("/freelanceAdPage/created_freelance_ad_page_list")
        context = {
            "form": form,
            "title": title
        }
        return render(request, 'update_ad_page.html', context)
    else:
        return redirect('/')

@login_required
def delete_ad_page(request, pk):
    if request.user.role == 1:
        freelance = AdPage.objects.get(id=pk)
        if request.method == "POST":
            freelance.delete()
            return redirect("/freelanceAdPage/created_freelance_ad_page_list")
        context = {
            "freelance": freelance,
        }
        return render(request, 'delete_ad_page.html', context)
    else:
        return redirect('/')

def review(request,ad):
    if request.user.is_anonymous == False and request.method == 'POST':
        user = request.user.username
        review = request.POST.get('review').strip()
        rating = request.POST.get('rating')
        ad = request.POST.get('ad')
        if (review==""):
            print("Review should not be empty!")
            return redirect('/freelanceAdPage/review/'+ad)
        if rateAndComment.objects.filter(user=user).exists():
            old = rateAndComment.objects.all().filter(ad=ad).filter(user=user)
            old.delete()
        new = rateAndComment.objects.create(user=user,ad=ad,review=review,rating=rating)
        new.save()
    unsorted_reviews = rateAndComment.objects.all().filter(ad=ad)
    reviews=sorted(list(unsorted_reviews.values()),key=lambda k:k['date'])[::-1]
    if request.user.is_anonymous:
        role = 3
    else:
        role = request.user.role
    return render(request, 'review.html',{'reviews':reviews,'ad':ad, 'role':role})

freelanceAdPage/templates/browse_page.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Browse Freelance Advertisement</title>
  </head>
  {% extends 'navbar.html' %} {% load static %} {% block content %}
  <body>
    <div class="container">
        <h1>Search Freelance Page</h1>
        <h5>Search for freelance offers here!</h5>
        <form>
            <div class="mb-3">
              <label for="search_freelance" class="form-label">Search Freelance</label>
              <input type="text" class="form-control" id="search_freelance">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <br>
        <div class="row">
          <div class="col">
            <div class="card" style="width: 18rem;">
              <img src="{% static 'image/Bowling_5_1080P.jpg'%}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">3D Rendering #1</h5>
                <p class="card-text">I will teach you how to render a 3D image in Blender</p>
                <a href="{% url 'freelanceAdPage:freelance_ad_page' %}" class="btn btn-primary">Check Page</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <img src="{% static 'image/Bowling_5_1080P.jpg'%}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">3D Rendering #2</h5>
                <p class="card-text">I will teach you how to render a 3D image in Blender</p>
                <a href="{% url 'freelanceAdPage:freelance_ad_page' %}" class="btn btn-primary">Check Page</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <img src="{% static 'image/Bowling_5_1080P.jpg'%}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">3D Rendering #3</h5>
                <p class="card-text">I will teach you how to render a 3D image in Blender</p>
                <a href="{% url 'freelanceAdPage:freelance_ad_page' %}" class="btn btn-primary">Check Page</a>
              </div>
            </div>
          </div>
        </div>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
  {% endblock %}
</html>

freelanceAdPage/templates/create_ad_page.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Create Freelance Page</title>
  </head>
  {% extends 'navbar.html' %} {% load static %} {% block content %}

  <body>
    <div class="container">
      <h1>Create Freelance Page</h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
              <label class="form-label">Freelance Title</label>
              {{ form.title }}
            </div>
            <div class="mb-3">
              <label class="form-label">Description</label>
              {{ form.description }}
            </div>
            <div class="mb-3">
              <label class="form-label">Additional Info</label>
              {{ form.additional_info }}
            </div>
            <div class="mb-3">
              <label class="form-label">Your Price</label>
              {{ form.price }}
            </div>      
            <div>
              {{ form.creator }}
            </div>            
            <input type="submit" value="Save" class="btn btn-primary">
        </form>
        <a href="{% url 'freelanceAdPage:created_freelance_ad_page_list' %}" class="btn btn-danger">Cancel</a>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
  {% endblock %}
</html>

freelanceAdPage/templates/freelance_ad_created_list.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Created Freelance Page List</title>
  </head>
  {% extends 'navbar.html' %} {% load static %} {% block content %}

  <body>
    <div class="container">
      <h1>Created Freelance Page List</h1>
      <div class="row">
        {% for ad in AdPage %}
        <div class="col-4">
            <div class="card">
              <img src="{% static 'image/Bowling_5_1080P.jpg'%}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{ad.title}}</h5>
                <p class="card-text">{{ad.description|slice:":50"}}</p>
                <p class="card-text">Set Price: {{ad.price}}</p>
                <a href="{% url 'freelanceAdPage:freelance_ad_page' ad.id %}" class="btn btn-primary">Check Page</a>
                <a href="{% url 'freelanceAdPage:update_ad_page' ad.id %}" class="btn btn-primary">Update Page</a>
                <a href="{% url 'freelanceAdPage:delete_ad_page' ad.id %}" class="btn btn-danger">Delete Page</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
        
        
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
  {% endblock %}
</html>

freelanceAdPage/templates/freelance_ad_page.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Freelance Page</title>
  </head>
  {% extends 'navbar.html' %} {% load static %} {% block content %}

  <body>
    <div class="container">
        <h1>{{ad.title}}</h1>
        <h4>Offered by:</h4>
        <h4 class="" style="display: inline-block;">{{ad.creator}}</h4>
        {% if role == 3 %}
        {% elif role == 2 %}
        <form action="{% url 'chat:chat'%}" method="POST" style="display: inline-block;">
            {% csrf_token %}
            <input type="hidden" name="target" id="target" value="{{ ad.creator}}"/>
            <input type="submit" value="💬" />
        </form>
        {% else %}
        {% endif %}
        <br>
        <div class="row">
            <div class="col-8">
                <img src="{% static 'image/Bowling_5_1080P.jpg'%}" class="img-fluid" alt="...">
                <h4>Information about this freelance</h4>
                <blockquote class="blockquote">
                  {{ad.description}}
                </blockquote>
            </div>
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">Price</h5>
                      <h6 class="card-subtitle mb-2">{{ad.price}}</h6>
                      <p class="card-text">{{ad.additional_info}}</p>
                      <a href="#" class="btn btn-primary">Continue to payment</a>
                    </div>
                  </div>
            </div>
        </div>
        <h3 class="text-center">Reviews</h3>
        {% if count == 0 %}
        <h4 class="text-center">No reviews yet!</h4>
        {% else %}
        <figure>
            <blockquote class="blockquote">
              {{ review.review }}
            </blockquote>
            <figcaption class="blockquote-footer">
              {{ review.user }}
            </figcaption>
        </figure>
        {% endif %}
        <div class="d-flex justify-content-center">
            <a class="btn btn-primary" href="{% url 'freelanceAdPage:review' ad.id %}" role="button">Add or see reviews</a>
        </div>
        
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
  {% endblock %}
</html>

freelanceAdPage/templates/review.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'review/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'freelanceAdPage:browse_page' %}">Browse Freelance</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User Portal
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          {% if request.user.is_anonymous %}
          <li><a class="dropdown-item" href="#">About</a></li>
          <li><a class="dropdown-item" href="{% url 'home:signup' %}">Register</a></li>
          <li><a class="dropdown-item" href="{% url 'home:login' %}">Login</a></li>
          {% else %}
          <li><a class="dropdown-item" href="#">About</a></li>
          <li><a class="dropdown-item" href="#">Dashboard</a></li>
          <li><a class="dropdown-item" href="{% url 'chat:chat' %}">Chat</a></li>
          <li><a class="dropdown-item" href="{% url 'home:logout' %}">Logout</a></li>
          {% endif %}
      </ul>
  </li>
</ul>
</div>
</div>
</nav>
<body>
    <div class="container djustify-content-center" style="width: 100%;height: 100%;">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-3">
                    <div class="flex-column mx-2 mb-2">
                        <div class="fw-bold fs-3">Rate and Comment Freelancer</div>
                        {% if role == 3 %}
                        {% elif role == 2 %}
                        <form align="left" action="{% url 'freelanceAdPage:review' ad %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="ad" id="ad" value="{{ ad }}"/>
                            <div class="mb-3">
                                <label class="form-label">Rate</label>
                                <input type="radio" name="rating" id="1" value="1"/>
                                <label for="1">1</label>
                                <input type="radio" name="rating" id="2" value="2"/>
                                <label for="2">2</label>
                                <input type="radio" name="rating" id="3" value="3"/>
                                <label for="3">3</label>
                                <input type="radio" name="rating" id="4" value="4"/>
                                <label for="4">4</label>
                                <input type="radio" name="rating" id="5" value="5"/>
                                <label for="5">5</label>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Comment</label>
                                <textarea type="text" class="form-control" name="review" id="review"></textarea>
                            </div>
                            <input class="btn btn-primary" type="submit" name="Submit Review">
                        </form>
                        {% else %}
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">Recent Review</h4>
                    </div>
                    <div class="comment-widgets m-b-20">
                        <div class="d-flex flex-row row mx-2">
                            {% for review in reviews %}
                            <div class="comment-text w-100">
                                <h5>{{ review.user }}</h5>
                                <script type="text/javascript">
                                    var stars = {{ review.rating }}
                                    if (stars == 1) {
                                        document.write("<div>"+"★☆☆☆☆"+"</div>");
                                    } else if (stars == 2) {
                                        document.write("<div>"+"★★☆☆☆"+"</div>");
                                    } else if (stars == 3) {
                                        document.write("<div>"+"★★★☆☆"+"</div>");
                                    } else if (stars == 4) {
                                        document.write("<div>"+"★★★★☆"+"</div>");
                                    } else {
                                        document.write("<div>"+"★★★★★"+"</div>");
                                    }
                                </script>
                                <script type="text/javascript">
                                    var dateObj = new Date("{{ review.date|escapejs }}");
                                    var month = dateObj.getUTCMonth() + 1; //months from 1-12
                                    var day = dateObj.getUTCDate();
                                    var year = dateObj.getUTCFullYear();
                                    document.write("<div class='comment-footer'>" + "<span>" + day + "/" + month + "/" + year + "</span>" + "</div>")
                                </script>
                                <p class="m-b-5 m-t-10">{{ review.review }}</p>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>